#To set a superuser like permission to execute the build
sudo: required

#Tell Travis we need a copy of docker running
services:
  - docker

##Series of action before run our tests or deploy our project
before_install:
  - docker build -t sanjaygorai/react-docker -f Dockerfile.dev .

##Run our test script and exit with code 0
script:
  - docker run -e CI=true sanjaygorai/react-docker npm run test
 
deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app:  "React-Docker"
  env:  "ReactDocker-env"
  bucket_name:  "elasticbeanstalk-eu-west-1-143607323522"
  bucket_path:  "React-Docker"
  on:
    branch: master
  access_key_id:  "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"



